---
# tasks file for apigee-opdk-setup-component
- block:

  - name: Install Apigee component for version {{ opdk_version }} or greater - {{ profile }}
    shell: '{{ apigee_setup }} -p {{ profile }} -f {{ opdk_installation_config_file }}'
    when: opdk_version | version_compare('4.16.01', '>=')

  - name: 10 second time delay for component boot
    pause:
      seconds: '{{ component_start_delay | default(10) }}'

  - name: Checking to see if failure was real by starting the components
    shell: '{{ apigee_all }} start'
    when: opdk_version | version_compare('4.16.01', '>=')

  rescue:

    - name: Checking to see if failure was real by starting the components
      shell: '{{ apigee_all }} start'
      when: opdk_version | version_compare('4.16.01', '>=')

- name: Additional time delay for component boot
  pause:
    minutes: '{{ component_start_delay | default(0) }}'
