---
# tasks file for apigee-opdk-setup-component
- name: Cache attributes attributes
  tags: ['cache']
  include_tasks: "cache.yml"

#- block:
#  - name: Include Apigee setup commands
#    include_tasks: setup-apigee-component.yml
#
#  rescue:
#    - name: Rescue for Apigee component installation
#      include_tasks: "rescue.yml"

- name: Install Apigee component {{ profile }} for Private Cloud {{ opdk_version }}
  become: yes
  command: '{{ apigee_setup }} -p {{ profile }} -f {{ opdk_installation_config_file }}'
  environment:
    http_proxy: "{{ http_proxy | default('') }}"
    https_proxy: "{{ https_proxy | default('') }}"
    no_proxy: "{{ no_proxy | default('') }}"
    PORT_TIMEOUT: '{{ port_timeout | default(60) }}'
    UP_TIMEOUT: '{{ up_timeout | default(60) }}'
  when: opdk_debug_mode is not defined or opdk_debug_mode | trim | lower == 'off'

- name: DEBUG_MODE - Install Apigee component {{ profile }} for Private Cloud {{ opdk_version }}
  become: yes
  command: '/usr/bin/bash -x {{ apigee_setup }} -p {{ profile }} -f {{ opdk_installation_config_file }}'
  environment:
    http_proxy: "{{ http_proxy | default('') }}"
    https_proxy: "{{ https_proxy | default('') }}"
    no_proxy: "{{ no_proxy | default('') }}"
    PORT_TIMEOUT: '{{ port_timeout | default(60) }}'
    UP_TIMEOUT: '{{ up_timeout | default(60) }}'
  when: opdk_debug_mode is defined and opdk_debug_mode | trim | lower == 'on'

- name: Wait for ready
  become: yes
  command: '{{ apigee_all }} wait_for_ready'
  when: validate_ready | default(true)
  environment:
    http_proxy: "{{ http_proxy | default('') }}"
    https_proxy: "{{ https_proxy | default('') }}"
    no_proxy: "{{ no_proxy | default('') }}"

- name: Validate component status
  become: yes
  command: '{{ apigee_all }} status'
  environment:
    http_proxy: "{{ http_proxy | default('') }}"
    https_proxy: "{{ https_proxy | default('') }}"
    no_proxy: "{{ no_proxy | default('') }}"

