---
# tasks file for apigee-opdk-setup-component
- name: Cache attributes attributes
  tags: ['cache']
  include_tasks: "cache.yml"

- name: Set for cassandra folder
  set_fact:
    create_folder: "{{ apigee_home }}/apigee-cassandra"
  when: profile == 'ds'

- name: Set for zookeeper folder
  set_fact:
    create_folder: "{{ apigee_home }}/apigee-zookeeper"
  when: profile == 'zk'

- name: Set for management server folder
  set_fact:
    create_folder: "{{ apigee_home }}/edge-management-server"
  when: profile == 'ms'

- name: Set for router folder
  set_fact:
    create_folder: "{{ apigee_home }}/edge-router"
  when: profile == 'r' or profile == 'rmp'

- name: Set for message processor folder
  set_fact:
    create_folder: "{{ apigee_home }}/edge-message-processor"
  when: profile == 'mp'

- name: Set for qpid folder
  set_fact:
    create_folder: "{{ apigee_home }}/apigee-qpidd"
  when: profile == 'qs'

- name: Set for postgresql folder
  set_fact:
    create_folder: "{{ apigee_home }}/apigee-postgresql"
  when: profile == 'pg'

- block:
  - name: Install Apigee component {{ profile }} for Private Cloud {{ opdk_version }}
    become: yes
    command: '{{ apigee_setup }} -p {{ profile }} -f {{ opdk_installation_config_file }}'
    args:
      creates: "{{ create_folder }}"
    environment:
      http_proxy: "{{ http_proxy | default('') }}"
      https_proxy: "{{ https_proxy | default('') }}"
      no_proxy: "{{ no_proxy | default('') }}"
      PORT_TIMEOUT: '{{ port_timeout | default(60) }}'
      UP_TIMEOUT: '{{ up_timeout | default(60) }}'
    when: opdk_debug_mode is not defined or opdk_debug_mode | trim | lower == 'off'

  - name: DEBUG_MODE - Install Apigee component {{ profile }} for Private Cloud {{ opdk_version }}
    become: yes
    command: '/usr/bin/bash -x {{ apigee_setup }} -p {{ profile }} -f {{ opdk_installation_config_file }}'
    args:
      creates: "{{ create_folder }}"
    environment:
      http_proxy: "{{ http_proxy | default('') }}"
      https_proxy: "{{ https_proxy | default('') }}"
      no_proxy: "{{ no_proxy | default('') }}"
      PORT_TIMEOUT: '{{ port_timeout | default(60) }}'
      UP_TIMEOUT: '{{ up_timeout | default(60) }}'
    when: opdk_debug_mode is defined and opdk_debug_mode | trim | lower == 'on'

  rescue:
    - name: Recovery for Qpid components
      include_tasks: rescue-qs.yml
      when: profile == 'qs'

    - name: Attempt to start component anyway
      shell: "{{ apigee_all }} start"

