---
# tasks file for apigee-opdk-setup-component
- name: Cache attributes attributes
  tags: ['cache']
  include_tasks: "cache.yml"

- block:
  - name: Include Apigee setup commands
    include_tasks: setup-apigee-component.yml

  rescue:
    - name: Rescue for Apigee component installation
      include_tasks: "{{ profile }}-rescue.yml"
      when: rescue.stat.exists

- name: Wait for ready
  become: yes
  command: '{{ apigee_all }} wait_for_ready'
  when: validate_ready | default(true)
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
    no_proxy: "{{ no_proxy }}"

- name: Validate component status
  become: yes
  command: '{{ apigee_all }} status'
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
    no_proxy: "{{ no_proxy }}"

