---
# tasks file for apigee-opdk-setup-component
- name: Cache attributes attributes
  tags: ['cache']
  include_tasks: "cache.yml"

- block:
  - name: Install Apigee component {{ profile }} for Private Cloud {{ opdk_version }}
    become: yes
    command: '{{ apigee_setup }} -p {{ profile }} -f {{ target_response_file_path }}'
    environment:
      http_proxy: "{{ http_proxy | default('') }}"
      https_proxy: "{{ https_proxy | default('') }}"
      no_proxy: "{{ no_proxy | default('') }}"
      PORT_TIMEOUT: '{{ port_timeout | default(60) }}'
      UP_TIMEOUT: '{{ up_timeout | default(60) }}'
    when: opdk_debug_mode is not defined or opdk_debug_mode | trim | lower == 'off'
    register: setup_log

  - name: Test Only Install Apigee component {{ profile }} for Private Cloud {{ opdk_version }}
    become: yes
    command: '{{ apigee_setup }} -p {{ profile }} -f {{ target_response_file_path }} -t'
    environment:
      http_proxy: "{{ http_proxy | default('') }}"
      https_proxy: "{{ https_proxy | default('') }}"
      no_proxy: "{{ no_proxy | default('') }}"
      PORT_TIMEOUT: '{{ port_timeout | default(60) }}'
      UP_TIMEOUT: '{{ up_timeout | default(60) }}'
    when: opdk_debug_mode is defined and opdk_debug_mode | trim | lower == 'on'
    register: setup_log

  rescue:
    - name: Repair node
      import_role:
        name: apigee-opdk-cassandra-repair
      when: profile == 'ds'

    - block:

      - name: Ensure that yum support is installed
        become: true
        yum:
          name: "{{ item }}"
          state: present
        with_items:
          - yum-utils
          - yum-plugin-priorities

      - name: Use Apigee Qpid Work Around
        become: true
        shell: yum --setopt=obsoletes=0 install apigee-qpidd -y

      - name: Install Apigee Qpid Component
        import_role:
          name: apigee-opdk-setup-component
        vars:
          profile: 'qs'

      when: profile == 'qs'

- name: Attempt to start component
  shell: "{{ apigee_all }} start"

- name: Wait for ready with no proxy
  become: yes
  command: '{{ apigee_all }} wait_for_ready'
  when: validate_ready | default(true)

