---
# tasks file for apigee-opdk-setup-component
- name: Use no proxy definitions
  include: with_no_proxy.yml
  when: https_proxy is not defined or https_proxy | trim == '' and http_proxy is not defined or http_proxy | trim == ''

- name: Use proxy definitions
  include: with_proxy.yml
  when: https_proxy is defined and https_proxy | trim != '' and http_proxy is defined and http_proxy | trim != ''

- name: Wait for ready
  become: yes
  ignore_errors: "{{ ignore_errors | default('no') }}"
  command: '{{ apigee_all }} wait_for_ready'
  when: validate_ready | default(true)

- name: Validate component status
  become: yes
  command: '{{ apigee_all }} status'

