---
- name: Setup utilities in cache
  cache:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
  - { key: 'nodetool', value: '{{ apigee_home }}/apigee-cassandra-client/bin/nodetool' }
  - { key: 'cqlsh', value: '{{ apigee_home }}/apigee-cassandra-client/bin/cqlsh' }
  - { key: 'cassandra_cli', value: '{{ apigee_home }}/apigee-cassandra-client/bin/cassandra-cli' }

