---
- name: Setup utilities in cache
  tags: ['cache']
  cache:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
  - { key: 'qpid_stat', value: '{{ apigee_home }}/apigee-qpidd/bin/qpid-stat' }
  - { key: 'check_queue_depth', value: '{{ apigee_home }}/apigee-qpidd/bin/check_queue_depth.py' }

