---
- name: Install Apigee component for version {{ opdk_version }} or greater with no proxy - {{ profile }}
  become: yes
  command: '{{ apigee_setup }} -p {{ profile }} -f {{ opdk_installation_config_file }}'
  when: opdk_debug_mode is not defined or opdk_debug_mode | trim | lower == 'off'
  environment:
    PORT_TIMEOUT: '{{ port_timeout | default(60) }}'
    UP_TIMEOUT: '{{ up_timeout | default(60) }}'

- name: DEBUG_MODE - Install Apigee component for version {{ opdk_version }} or greater with no proxy - {{ profile }}
  become: yes
  command: '{{ apigee_setup }} -p {{ profile }} -f {{ opdk_installation_config_file }}'
  when: opdk_debug_mode is defined and opdk_debug_mode | trim | lower == 'on'
  environment:
    PORT_TIMEOUT: '{{ port_timeout | default(60) }}'
    UP_TIMEOUT: '{{ up_timeout | default(60) }}'


- name: Wait for ready with no proxy
  become: yes
  command: '{{ apigee_all }} wait_for_ready'
  when: validate_ready | default(true)
