---
- name: Install Apigee component for version {{ opdk_version }} or greater with no proxy - {{ profile }}
  command: '{{ apigee_setup }} -p {{ profile }} -f {{ opdk_installation_config_file }}'
  when: opdk_debug_mode is not defined or opdk_debug_mode | trim | lower == 'off'

- name: Install Apigee component for version {{ opdk_version }} or greater with no proxy - {{ profile }}
  command: '{{ apigee_setup }} -p {{ profile }} -f {{ opdk_installation_config_file }}'
  when: opdk_debug_mode is defined and opdk_debug_mode | trim | lower == 'on'

- name: Wait for ready with no proxy
  command: '{{ apigee_all }} wait_for_ready'
  when: validate_ready | default(true)
